/**
 * 国家到国旗的映射
 */

export const COUNTRY_FLAGS: Record<string, string> = {
  "Russia": "🇷🇺",
  "Denmark": "🇩🇰",
  "USA": "🇺🇸",
  "France": "🇫🇷",
  "Brazil": "🇧🇷",
  "Germany": "🇩🇪",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Finland": "🇫🇮",
  "Poland": "🇵🇱",
  "Ukraine": "🇺🇦",
  "CIS": "🇨🇬",
  "Australia": "🇦🇺",
  "Canada": "🇨🇦",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Spain": "🇪🇸",
  "Portugal": "🇵🇹",
  "Italy": "🇮🇹",
  "Switzerland": "🇨🇭",
  "Austria": "🇦🇹",
  "Czech Republic": "🇨🇿",
  "Slovakia": "🇸🇰",
  "Hungary": "🇭🇺",
  "Romania": "🇷🇴",
  "Bulgaria": "🇧🇬",
  "Croatia": "🇭🇷",
  "Serbia": "🇷🇸",
  "Montenegro": "🇲🇪",
  "Bosnia and Herzegovina": "🇧🇦",
  "Slovenia": "🇸🇮",
  "Estonia": "🇪🇪",
  "Latvia": "🇱🇻",
  "Lithuania": "🇱🇹",
  "China": "🇨🇳",
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Thailand": "🇹🇭",
  "Vietnam": "🇻🇳",
  "Singapore": "🇸🇬",
  "India": "🇮🇳",
  "Israel": "🇮🇱",
  "Turkey": "🇹🇷",
  "UAE": "🇦🇪",
  "Saudi Arabia": "🇸🇦",
  "Egypt": "🇪🇬",
  "South Africa": "🇿🇦",
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Peru": "🇵🇪",
  "Colombia": "🇨🇴",
  "Mexico": "🇲🇽",
  "New Zealand": "🇳🇿",
  "UK": "🇬🇧",
  "United Kingdom": "🇬🇧",
  "Ireland": "🇮🇪",
  "Iceland": "🇮🇸",
  "Greece": "🇬🇷",
  "Cyprus": "🇨🇾",
  "Malta": "🇲🇹",
  "Luxembourg": "🇱🇺",
  "Liechtenstein": "🇱🇮",
  "Monaco": "🇲🇨",
  "Andorra": "🇦🇩",
  "San Marino": "🇸🇲",
  "Vatican City": "🇻🇦",
  "Belarus": "🇧🇾",
  "Kazakhstan": "🇰🇿",
  "Uzbekistan": "🇺🇿",
  "Turkmenistan": "🇹🇲",
  "Kyrgyzstan": "🇰🇬",
  "Tajikistan": "🇹🇯",
  "Armenia": "🇦🇲",
  "Azerbaijan": "🇦🇿",
  "Georgia": "🇬🇪",
  "Moldova": "🇲🇩",
  "United States": "🇺🇸",
  "Uruguay": "🇺🇾",
  "Paraguay": "🇵🇾",
  "Bolivia": "🇧🇴",
  "Ecuador": "🇪🇨",
  "Venezuela": "🇻🇪",
  "Guyana": "🇬🇾",
  "Suriname": "🇸🇷",
  "French Guiana": "🇬🇫",
  "Guatemala": "🇬🇹",
  "Belize": "🇧🇿",
  "El Salvador": "🇸🇻",
  "Honduras": "🇭🇳",
  "Nicaragua": "🇳🇮",
  "Costa Rica": "🇨🇷",
  "Panama": "🇵🇦",
  "Cuba": "🇨🇺",
  "Jamaica": "🇯🇲",
  "Haiti": "🇭🇹",
  "Dominican Republic": "🇩🇴",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Jordan": "🇯🇴",
  "Lebanon": "🇱🇧",
  "Syria": "🇸🇾",
  "Yemen": "🇾🇪",
  "Oman": "🇴🇲",
  "Qatar": "🇶🇦",
  "Bahrain": "🇧🇭",
  "Kuwait": "🇰🇼",
  "Pakistan": "🇵🇰",
  "Bangladesh": "🇧🇩",
  "Sri Lanka": "🇱🇰",
  "Myanmar": "🇲🇲",
  "Cambodia": "🇰🇭",
  "Laos": "🇱🇦",
  "Malaysia": "🇲🇾",
  "Indonesia": "🇮🇩",
  "Philippines": "🇵🇭",
  "Brunei": "🇧🇳",
  "Maldives": "🇲🇻",
  "Nepal": "🇳🇵",
  "Bhutan": "🇧🇹",
  "Mongolia": "🇲🇳",
  "North Korea": "🇰🇵",
  "Taiwan": "🇹🇼",
  "Hong Kong": "🇭🇰",
  "Macau": "🇲🇴",
  "Fiji": "🇫🇯",
  "Papua New Guinea": "🇵🇬",
  "Solomon Islands": "🇸🇧",
  "Vanuatu": "🇻🇺",
  "Samoa": "🇼🇸",
  "Tonga": "🇹🇴",
  "Kiribati": "🇰🇮",
  "Tuvalu": "🇹🇻",
  "Nauru": "🇳🇷",
  "Palau": "🇵🇼",
  "Marshall Islands": "🇲🇭",
  "Micronesia": "🇫🇲",
  "Unknown": "❓",
};

/**
 * 获取国家的国旗
 */
export function getCountryFlag(country: string): string {
  return COUNTRY_FLAGS[country] || "🏳️";
}
