/**
 * 国家到国旗的映射
 */

export const COUNTRY_FLAGS: Record<string, string> = {
  Russia: "🇷🇺",
  Denmark: "🇩🇰",
  USA: "🇺🇸",
  France: "🇫🇷",
  Brazil: "🇧🇷",
  Germany: "🇩🇪",
  Sweden: "🇸🇪",
  Norway: "🇳🇴",
  Finland: "🇫🇮",
  Poland: "🇵🇱",
  Ukraine: "🇺🇦",
  CIS: "🇨🇬",
  Australia: "🇦🇺",
  Canada: "🇨🇦",
  Netherlands: "🇳🇱",
  Belgium: "🇧🇪",
  Spain: "🇪🇸",
  Portugal: "🇵🇹",
  Italy: "🇮🇹",
  Switzerland: "🇨🇭",
  Austria: "🇦🇹",
  "Czech Republic": "🇨🇿",
  Slovakia: "🇸🇰",
  Hungary: "🇭🇺",
  Romania: "🇷🇴",
  Bulgaria: "🇧🇬",
  Croatia: "🇭🇷",
  Serbia: "🇷🇸",
  Montenegro: "🇲🇪",
  "Bosnia and Herzegovina": "🇧🇦",
  Slovenia: "🇸🇮",
  Estonia: "🇪🇪",
  Latvia: "🇱🇻",
  Lithuania: "🇱🇹",
  China: "🇨🇳",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  Thailand: "🇹🇭",
  Vietnam: "🇻🇳",
  Singapore: "🇸🇬",
  India: "🇮🇳",
  Israel: "🇮🇱",
  Turkey: "🇹🇷",
  UAE: "🇦🇪",
  "Saudi Arabia": "🇸🇦",
  Egypt: "🇪🇬",
  "South Africa": "🇿🇦",
  Argentina: "🇦🇷",
  Chile: "🇨🇱",
  Peru: "🇵🇪",
  Colombia: "🇨🇴",
  Mexico: "🇲🇽",
  "New Zealand": "🇳🇿",
  UK: "🇬🇧",
  "United Kingdom": "🇬🇧",
  Ireland: "🇮🇪",
  Iceland: "🇮🇸",
  Greece: "🇬🇷",
  Cyprus: "🇨🇾",
  Malta: "🇲🇹",
  Luxembourg: "🇱🇺",
  Liechtenstein: "🇱🇮",
  Monaco: "🇲🇨",
  Andorra: "🇦🇩",
  "San Marino": "🇸🇲",
  "Vatican City": "🇻🇦",
  Belarus: "🇧🇾",
  Kazakhstan: "🇰🇿",
  Uzbekistan: "🇺🇿",
  Turkmenistan: "🇹🇲",
  Kyrgyzstan: "🇰🇬",
  Tajikistan: "🇹🇯",
  Armenia: "🇦🇲",
  Azerbaijan: "🇦🇿",
  Georgia: "🇬🇪",
  Moldova: "🇲🇩",
  "United States": "🇺🇸",
  Uruguay: "🇺🇾",
  Paraguay: "🇵🇾",
  Bolivia: "🇧🇴",
  Ecuador: "🇪🇨",
  Venezuela: "🇻🇪",
  Guyana: "🇬🇾",
  Suriname: "🇸🇷",
  "French Guiana": "🇬🇫",
  Guatemala: "🇬🇹",
  Belize: "🇧🇿",
  "El Salvador": "🇸🇻",
  Honduras: "🇭🇳",
  Nicaragua: "🇳🇮",
  "Costa Rica": "🇨🇷",
  Panama: "🇵🇦",
  Cuba: "🇨🇺",
  Jamaica: "🇯🇲",
  Haiti: "🇭🇹",
  "Dominican Republic": "🇩🇴",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Jordan: "🇯🇴",
  Lebanon: "🇱🇧",
  Syria: "🇸🇾",
  Yemen: "🇾🇪",
  Oman: "🇴🇲",
  Qatar: "🇶🇦",
  Bahrain: "🇧🇭",
  Kuwait: "🇰🇼",
  Pakistan: "🇵🇰",
  Bangladesh: "🇧🇩",
  "Sri Lanka": "🇱🇰",
  Myanmar: "🇲🇲",
  Cambodia: "🇰🇭",
  Laos: "🇱🇦",
  Malaysia: "🇲🇾",
  Indonesia: "🇮🇩",
  Philippines: "🇵🇭",
  Brunei: "🇧🇳",
  Maldives: "🇲🇻",
  Nepal: "🇳🇵",
  Bhutan: "🇧🇹",
  Mongolia: "🇲🇳",
  "North Korea": "🇰🇵",
  Taiwan: "🇹🇼",
  "Hong Kong": "🇭🇰",
  Macau: "🇲🇴",
  Fiji: "🇫🇯",
  "Papua New Guinea": "🇵🇬",
  "Solomon Islands": "🇸🇧",
  Vanuatu: "🇻🇺",
  Samoa: "🇼🇸",
  Tonga: "🇹🇴",
  Kiribati: "🇰🇮",
  Tuvalu: "🇹🇻",
  Nauru: "🇳🇷",
  Palau: "🇵🇼",
  "Marshall Islands": "🇲🇭",
  Micronesia: "🇫🇲",
  Unknown: "❓",
};

/**
 * 获取国家的国旗
 */
export function getCountryFlag(country: string): string {
  return COUNTRY_FLAGS[country] || "🏳️";
}

/**
 * 国家英文到中文的映射
 */
export const COUNTRY_CHINESE: Record<string, string> = {
  Russia: "俄罗斯",
  Denmark: "丹麦",
  USA: "美国",
  France: "法国",
  Brazil: "巴西",
  Germany: "德国",
  Sweden: "瑞典",
  Norway: "挪威",
  Finland: "芬兰",
  Poland: "波兰",
  Ukraine: "乌克兰",
  CIS: "独联体",
  Australia: "澳大利亚",
  Canada: "加拿大",
  Netherlands: "荷兰",
  Belgium: "比利时",
  Spain: "西班牙",
  Portugal: "葡萄牙",
  Italy: "意大利",
  Switzerland: "瑞士",
  Austria: "奥地利",
  "Czech Republic": "捷克",
  Slovakia: "斯洛伐克",
  Hungary: "匈牙利",
  Romania: "罗马尼亚",
  Bulgaria: "保加利亚",
  Croatia: "克罗地亚",
  Serbia: "塞尔维亚",
  Montenegro: "黑山",
  "Bosnia and Herzegovina": "波黑",
  Slovenia: "斯洛文尼亚",
  Estonia: "爱沙尼亚",
  Latvia: "拉脱维亚",
  Lithuania: "立陶宛",
  China: "中国",
  Japan: "日本",
  "South Korea": "韩国",
  Thailand: "泰国",
  Vietnam: "越南",
  Singapore: "新加坡",
  India: "印度",
  Israel: "以色列",
  Turkey: "土耳其",
  UAE: "阿联酋",
  "Saudi Arabia": "沙特",
  Egypt: "埃及",
  "South Africa": "南非",
  Argentina: "阿根廷",
  Chile: "智利",
  Peru: "秘鲁",
  Colombia: "哥伦比亚",
  Mexico: "墨西哥",
  "New Zealand": "新西兰",
  UK: "英国",
  "United Kingdom": "英国",
  Ireland: "爱尔兰",
  Iceland: "冰岛",
  Greece: "希腊",
  Cyprus: "塞浦路斯",
  Malta: "马耳他",
  Luxembourg: "卢森堡",
  Liechtenstein: "列支敦士登",
  Monaco: "摩纳哥",
  Andorra: "安道尔",
  "San Marino": "圣马力诺",
  "Vatican City": "梵蒂冈",
  Belarus: "白俄罗斯",
  Kazakhstan: "哈萨克斯坦",
  Uzbekistan: "乌兹别克斯坦",
  Turkmenistan: "土库曼斯坦",
  Kyrgyzstan: "吉尔吉斯斯坦",
  Tajikistan: "塔吉克斯坦",
  Armenia: "亚美尼亚",
  Azerbaijan: "阿塞拜疆",
  Georgia: "格鲁吉亚",
  Moldova: "摩尔多瓦",
  "United States": "美国",
  Uruguay: "乌拉圭",
  Paraguay: "巴拉圭",
  Bolivia: "玻利维亚",
  Ecuador: "厄瓜多尔",
  Venezuela: "委内瑞拉",
  Guyana: "圭亚那",
  Suriname: "苏里南",
  "French Guiana": "法属圭亚那",
  Guatemala: "危地马拉",
  Belize: "伯利兹",
  "El Salvador": "萨尔瓦多",
  Honduras: "洪都拉斯",
  Nicaragua: "尼加拉瓜",
  "Costa Rica": "哥斯达黎加",
  Panama: "巴拿马",
  Cuba: "古巴",
  Jamaica: "牙买加",
  Haiti: "海地",
  "Dominican Republic": "多米尼加",
  Iran: "伊朗",
  Iraq: "伊拉克",
  Jordan: "约旦",
  Lebanon: "黎巴嫩",
  Syria: "叙利亚",
  Yemen: "也门",
  Oman: "阿曼",
  Qatar: "卡塔尔",
  Bahrain: "巴林",
  Kuwait: "科威特",
  Pakistan: "巴基斯坦",
  Bangladesh: "孟加拉国",
  "Sri Lanka": "斯里兰卡",
  Myanmar: "缅甸",
  Cambodia: "柬埔寨",
  Laos: "老挝",
  Malaysia: "马来西亚",
  Indonesia: "印尼",
  Philippines: "菲律宾",
  Brunei: "文莱",
  Maldives: "马尔代夫",
  Nepal: "尼泊尔",
  Bhutan: "不丹",
  Mongolia: "蒙古",
  "North Korea": "朝鲜",
  Taiwan: "台湾",
  "Hong Kong": "香港",
  Macau: "澳门",
  Fiji: "斐济",
  "Papua New Guinea": "巴布亚新几内亚",
  "Solomon Islands": "所罗门群岛",
  Vanuatu: "瓦努阿图",
  Samoa: "萨摩亚",
  Tonga: "汤加",
  Kiribati: "基里巴斯",
  Tuvalu: "图瓦卢",
  Nauru: "瑙鲁",
  Palau: "帕劳",
  "Marshall Islands": "马绍尔群岛",
  Micronesia: "密克罗尼西亚",
  Unknown: "未知",
};

/**
 * 获取国家的中文名称
 */
export function getCountryChinese(country: string): string {
  return COUNTRY_CHINESE[country] || country;
}
